---

- name: install packages
  apt: name={{ item }} state=present update_cache=yes
  with_items:
    - python-psycopg2
    - postgresql
    - postgresql-contrib

- name: create postgresql database
  sudo: yes
  sudo_user: postgres
  postgresql_db: name="{{ database_name }}"
                 encoding='UTF-8'
                 lc_collate='en_US.UTF-8'
                 lc_ctype='en_US.UTF-8'

- name: create postgresql user
  sudo: yes
  sudo_user: postgres
  postgresql_user: db="{{ database_name }}"
                   name="{{ db_username }}"
                   password="{{ db_password }}"
                   role_attr_flags=SUPERUSER

- name: postgres listens all address
  lineinfile: dest=/etc/postgresql/9.3/main/postgresql.conf
              line="listen_addresses = '*'"
              state=present

- name: postgres accepts all connections
  lineinfile: dest=/etc/postgresql/9.3/main/pg_hba.conf
              line="host\tall\tall\t0.0.0.0/0\tmd5"
              state=present

- name: restart postgres service
  service: name=postgresql state=restarted
