---

- name: install packages
  apt: name={{ item }} state=present update_cache=yes
  with_items:
    - python3-dev
    - python3-pip
    - python3-setuptools
    - libpq-dev
    - ruby-sass
    - python3-tk

- name: install python requirements, from project repo
  sudo: yes
  pip: requirements="{{ app_dir }}/requirements.txt"
       executable=pip3

- name: (flask) sync db
  shell: "echo run python3 ..."
